name: MedMinder
options:
  bundleIdPrefix: com.antigravity
  deploymentTarget:
    iOS: "15.0"
targets:
  MedMinder:
    type: application
    platform: iOS
    sources:
      - MedMinder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antigravity.MedMinder
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
